[connections.mysql_countries]
dialect = "mysql"
host = "localhost"
database = "2_viikkot3"
username = "veera"
password = "riisimur"

[connections.mysql_weather]
dialect = "mysql"
host = "localhost"
database = "weather_db"
username = "veera"
password = "riisimur"
